language: generic
script:
- make ci
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: pages
  local-dir: out
  skip-cleanup: true
  deploy_key: deploy_key
  edge:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_ffea4e724a49_key -iv $encrypted_ffea4e724a49_iv -in deploy_key.enc -out deploy_key -d
